# NFL Game Predictions

This chapter is an exposition on experiments using the [NFL predictions package](https://github.com/przybylee/NFLpredictions).  This package is designed to predict the outcomes of NFL games in terms of win probability, point spread, and point totals.  In the first few sections, we will describe each method of the point spread and win probability models.  In the final section, we will compare the models and how they perform against betting market lines.  At this point, we find that the simple models offered by this package are outperformed by the betting market lines, but they do provide a reasonable baseline for future model development.

## Win Probability Model

The simplest model in the package is a logistic regression model for win probability.  Assuming $J$ teams playing a total of $N$ games, our model starts with a $(N+2) \times (J+1)$ design matrix $X$ where

\begin{equation}
  (\#eq:design-matrix-nfl)
  X_{ij} = \begin{cases}
    \phantom{-}1 & \text{  if  } i > N\:\text{or}\:j = J + 1\\
    \phantom{-}1 & \text{  if  } \text{team } j \text{ is the home team in game } i\\
   -1 & \text{  if  } \text{team } j \text{ is the away team in game } i
  \end{cases}
\end{equation}

We let the last column be all equal to 1 to represent the effect for home field advantage.  We let the last row equal 1 to make the matrix have full column rank and center the team effect estimates at 0.  The response, $\mathbf{w}$, is a binary vector of length $N+ 1$ where $w_i = 1$ if the home team won game $i$ and $w_i = 0$ otherwise.  We use the logit link function, meaning that we assume

\begin{equation}
\begin{split}
  &w_i \sim \text{Bernoulli}(\pi_i) \\
  &\text{logit}(\pi_i) = X_i \tau
\end{split}
\end{equation}

where $\tau$ is a vector of length $J+1$ containing the team effects and the home field advantage effect.  We fit this model using maximum likelihood estimation, which is implemented in the `glm` function in R.  The fitted model can then be used to predict the win probability for any game by plugging in the appropriate values for the home and away teams.

## Point Spread Model

The point spread model uses the same design matrix, $X$ as was used in the win probability model.  Instead of a binary response, we let have a continuous response $\mathbf{y}\in\mathbb{R}^{N+1}$ where $y_i$ equals the home team's score minus the away team's score in game $i\le N$, and $y_{N+1} = 0$.  We perform linear regression to solve the equation

\begin{equation}
  (#eq:spread-eq-nfl)
  X\hat{\beta} = \mathbf{y}.
\end{equation}

We interpret the solution $\hat{\beta}$ as our best linear unbiased estimator (BLUE) of team effects, where $\hat{\beta}_j$ is the effect of team $j \le J$, where league average is $0$, and $\hat{\beta}_{J+1}$ is the effect of home field advantage, assumed to be uniform across the league. On a game by game, level, we are assuming the margin of victory for the home team is given by 

\begin{equation}
  {y}_i = \beta_{\text{home}[i]} - \beta_{\text{away}[i]} + \beta_{J+1} + \varepsilon_i, 
\end{equation}

where $\varepsilon_1, ...,\varepsilon_N$ are independent, identically distributed, and have mean 0.  There are a couple of obvious ways we can derive a win probability from this model's estimates.

The simpler way to estimate win probability using the point spread model is to assume that the $\varepsilon_1, ..., \varepsilon_N \simiid N(0,\sigma^2)$.  After fitting the model, we obtain the estimate $\hat{y} := X\hat{\beta}$, and the estimate for $\sigma$ is obtained in the usual way, by dividing the sum of squared errors by degrees of freedom.  The degrees of freedom equals the number of observations minus the column rank of $X$.

\begin{equation}
\hat{\sigma}^2 = \frac{1}{N - J}\sum_{j = 1}^{N+1}(y_j - \hat{y}_j)^2
\end{equation}

## Model Comparison


